### ISSUE TITLE
Assignment 5 - Peer Review for Group 10

### ISSUE THREAD

**Issue by impossiblity** [bounswe/bounswe2016group1#10]
### Activity Diagram
- The diagram contains a lot of detailed activities, which is nice.
- Adding labels to arrows and clarifying IF clauses would increase readability.
- I believe each activity should have the option to redirect the user to the main page instead of the login page. I think this is a slight mistake.
- I think the "create new content" workflow should be serially connected, rather than parallel. The user should enter the title, write the content and tag it in a sequence instead of doing only one of those things.
- I think the guest user should be able to search for content. I am not sure if recommendations should be made to a guest user, since they don't have a profile you can use to create personal recommendations.

### Class Diagram
- The class diagram clearly describes how classes are composed of other classes. The attributes and functions also seem relevant and sufficient for each class.
- Relations other than composition are not captured in this diagram. For example, a registered user can create multiple posts and comments. The system can recommend contents to the users. These types of relations can also be shown with arrows.
- I believe an inheritance hierarchy would be relevant among different types of users. For example, a Guest is the most basic type of user that can view posts and search content. A registered user can create content and write comments on top of that. The admin is more powerful and destroy other people's posts/comments and profiles. Using inheritance would signify this hierarchical relationship, while preventing redundant repetitions. 

### Use Case Diagram
- This diagram clearly captures all possible use cases. 
- I believe guest user should be able to search, and the admin should at least have all the capabilities of a guest user. For example, they should be able to view content before deleting.
- Example use case descriptions are missing.

### Sequence Diagrams
- These diagrams show the simple interaction between system components for some fundamental use cases.
- The labels of entities could be more specific. For example, only a registered user can follow a tag, and the tags exist only on the database dedicated for posts. 
- I am not sure if a search component is necessary, since it is only an SQL command from the system to the database.
- Feedback to the user is missing when they want to see popular tags.

**Comment by osmannnurikar** [comment]
Referencing Sequence Diagrams/Item 3 in your review:
Not that simple. Search service decides which queries to run after runnig some algorithms with the given parameters. Database is nothing but pure data as you know.
