### ISSUE TITLE
This repository needs a good wiki page

### ISSUE THREAD

**Issue by guneykan** [bounswe/bounswe2016group1#2]
We need to create a wiki page for this  repository until 17.02.2016.

**Comment by Mertcikla** [comment]
It is now slightly less empty.

**Comment by impossiblity** [comment]
I have finished the template and added what's sent to me by other people. You can either edit the relevant page or send me an e-mail and I'll copy & paste it.

**Comment by uskudarli** [comment]
Creating a template is a good idea.

However, direct editing from your team members is the right way to go.

Please do not go the route of mailing information to someone who puts it on
your repository.

We are very much concerned about everyone getting experience in using, not
only using, but using the software development tools and communication
(written, oral, ...) effectively.

Look forward to the participation by all of you.
